---
apiVersion: v1
kind: Namespace
metadata:
  name: '04076665'
  annotations:
    openshift.io/sa.scc.mcs: s0:c1,c0
    openshift.io/sa.scc.supplemental-groups: 1000000000/10000
    openshift.io/sa.scc.uid-range: 1000000000/10000
  labels:
    kubernetes.io/metadata.name: default
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: unrestricted-scc
allowHostNetwork: true  # Allow host network usage
allowPrivilegedContainer: true  # Allow privileged containers
allowPrivilegeEscalation: true  # Allow privilege escalation
allowHostPorts: true  # Allow the use of host ports
allowedCapabilities:
  - NET_ADMIN  # Allow NET_ADMIN capability
  - NET_RAW  # Allow NET_RAW capability
  - SYS_ADMIN  # Allow SYS_ADMIN capability
seccompProfiles:
  - "*"  # Allow any seccomp profile
runAsUser:
  type: RunAsAny  # Allow any UID
seLinuxContext:
  type: RunAsAny  # Allow any SELinux context
fsGroup:
  type: RunAsAny  # Allow any fsGroup
volumes:
  - hostPath  # Allow use of hostPath volumes
  - projected
  - secret
  - configMap
  - emptyDir
  - nfs
  - persistentVolumeClaim
  - downwardAPI
  - gcePersistentDisk
  - awsElasticBlockStore
  - cephFS
  - iscsi
  - rbd
  - cinder
  - glusterfs
  - azureDisk
users:
  - system:serviceaccount:04076665:default  # Allow the default service account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-test
  namespace: '04076665'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-test
  template:
    metadata:
      labels:
        app: iperf-test
    spec:
      hostNetwork: true
      securityContext:
        runAsUser: 1000000000
      nodeName: hub-ctlplane-0.5g-deployment.lab
      containers:
        - name: iperf-server
          image: quay.io/midu/iperf3:latest
          command: ["iperf3", "-s"]
          ports:
            - containerPort: 5201
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
            runAsUser: 1000000000

        - name: iperf-client
          image: quay.io/midu/iperf3:latest
          command:
            - /bin/sh
            - -c
            - "sleep 10; iperf3 -c 127.0.0.1 -t 60"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
            runAsUser: 1000000000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpdump-stress
  namespace: '04076665'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpdump-stress
  template:
    metadata:
      labels:
        app: tcpdump-stress
    spec:
      serviceAccountName: default  # Explicitly specify SA using unrestricted-scc
      hostNetwork: true
      securityContext:
        runAsUser: 1000000000
      nodeName: hub-ctlplane-0.5g-deployment.lab
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - iperf-test
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: tcpdump-golang-sockets
          image: quay.io/midu/tcpdump:golang-sockets
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN                 # Add SYS_ADMIN to allow low-level networking
            seccompProfile:
              type: RuntimeDefault          # Use default security profile
            allowPrivilegeEscalation: true  # Allow privilege escalation
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"