---
apiVersion: v1
kind: Namespace
metadata:
  name: '04076665'
  annotations:
    openshift.io/sa.scc.mcs: s0:c1,c0
    openshift.io/sa.scc.supplemental-groups: 1000000000/10000
    openshift.io/sa.scc.uid-range: 1000000000/10000
  labels:
    kubernetes.io/metadata.name: default
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: tcpdump-scc
allowHostNetwork: true
allowPrivilegedContainer: false
allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
users:
  - system:serviceaccount:04076665:default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-test
  namespace: '04076665'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-test
  template:
    metadata:
      labels:
        app: iperf-test
    spec:
      hostNetwork: true
      nodeName: hub-ctlplane-0.5g-deployment.lab  # Specify the exact node name here
      containers:
        - name: iperf-server
          image: quay.io/midu/iperf3:latest
          command: ["iperf3", "-s"]
          ports:
            - containerPort: 5201
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW

        - name: iperf-client
          image: quay.io/midu/iperf3:latest
          command:
            - /bin/sh
            - -c
            - "sleep 10; iperf3 -c 127.0.0.1 -t 60"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpdump-stress
  namespace: '04076665'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpdump-stress
  template:
    metadata:
      labels:
        app: tcpdump-stress
    spec:
      hostNetwork: true
      nodeName: hub-ctlplane-0.5g-deployment.lab  # Specify the exact node name here
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - iperf-test
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: tcpdump
          image: quay.io/midu/tcpdump:latest
          command:
            - /bin/sh
            - -c
            - |
              for I in $(seq 1 200); do (tcpdump -qnni any &) ; done
              sleep infinity
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
